fix: build errors for WASI target
* The `cargo build` command failed for the WASI target with the
  following error:

```
warning: /home/dennis/code/mcp/rust-sdk/crates/rmcp/Cargo.toml: unused manifest key: dependencies.rmcp-macros.version
warning: /home/dennis/code/mcp/rust-sdk/examples/simple-chat-client/Cargo.toml: unused manifest key: dependencies.rmcp.no-default-features
error: There are multiple `wasi` packages in your project, and the specification `wasi` is ambiguous.
Please re-run this command with one of the following specifications:
  wasi@0.1.5
  wasi@0.14.2+wasi-0.2.4
```

It seems that the command got confused about the package name when
trying to build on a fresh machine. The solution for this is the
renaming of the package.

* The commands in the documentation are changed accordingly.
* Enhance also the documentation a little bit.